apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-master
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - host: www.appka.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traffic-master
                port:
                  number: 80
  tls:
    - secretName: tls-staging-cert
      hosts:
        - www.appka.site
